/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TeamsRouteImport } from "./routes/teams";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as RegisteredRouteImport } from "./routes/registered";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as PlacementsRouteImport } from "./routes/placements";
import { Route as PeerLearningRouteImport } from "./routes/peer-learning";
import { Route as NotificationsRouteImport } from "./routes/notifications";
import { Route as MaterialsRouteImport } from "./routes/materials";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as ForumRouteImport } from "./routes/forum";
import { Route as FeedRouteImport } from "./routes/feed";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as ChatRouteImport } from "./routes/chat";
import { Route as AssistantRouteImport } from "./routes/assistant";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as EventsIndexRouteImport } from "./routes/events.index";
import { Route as ClubsIndexRouteImport } from "./routes/clubs.index";
import { Route as BookingIndexRouteImport } from "./routes/booking.index";
import { Route as AdminIndexRouteImport } from "./routes/admin.index";
import { Route as EventsEventIdRouteImport } from "./routes/events.$eventId";
import { Route as ClubsClubIdRouteImport } from "./routes/clubs.$clubId";
import { Route as AdminEventsRouteImport } from "./routes/admin.events";
import { Route as AdminAnalyticsRouteImport } from "./routes/admin.analytics";
import { Route as BookingConfirmedBookingIdRouteImport } from "./routes/booking.confirmed.$bookingId";
const TeamsRoute = TeamsRouteImport.update({
  id: "/teams",
  path: "/teams",
  getParentRoute: () => rootRouteImport,
});
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
});
const RegisteredRoute = RegisteredRouteImport.update({
  id: "/registered",
  path: "/registered",
  getParentRoute: () => rootRouteImport,
});
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
});
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
});
const PlacementsRoute = PlacementsRouteImport.update({
  id: "/placements",
  path: "/placements",
  getParentRoute: () => rootRouteImport,
});
const PeerLearningRoute = PeerLearningRouteImport.update({
  id: "/peer-learning",
  path: "/peer-learning",
  getParentRoute: () => rootRouteImport,
});
const NotificationsRoute = NotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => rootRouteImport,
});
const MaterialsRoute = MaterialsRouteImport.update({
  id: "/materials",
  path: "/materials",
  getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
});
const ForumRoute = ForumRouteImport.update({
  id: "/forum",
  path: "/forum",
  getParentRoute: () => rootRouteImport,
});
const FeedRoute = FeedRouteImport.update({
  id: "/feed",
  path: "/feed",
  getParentRoute: () => rootRouteImport,
});
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
});
const ChatRoute = ChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => rootRouteImport,
});
const AssistantRoute = AssistantRouteImport.update({
  id: "/assistant",
  path: "/assistant",
  getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: "/events/",
  path: "/events/",
  getParentRoute: () => rootRouteImport,
});
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: "/clubs/",
  path: "/clubs/",
  getParentRoute: () => rootRouteImport,
});
const BookingIndexRoute = BookingIndexRouteImport.update({
  id: "/booking/",
  path: "/booking/",
  getParentRoute: () => rootRouteImport,
});
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => rootRouteImport,
});
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: "/events/$eventId",
  path: "/events/$eventId",
  getParentRoute: () => rootRouteImport,
});
const ClubsClubIdRoute = ClubsClubIdRouteImport.update({
  id: "/clubs/$clubId",
  path: "/clubs/$clubId",
  getParentRoute: () => rootRouteImport,
});
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: "/admin/events",
  path: "/admin/events",
  getParentRoute: () => rootRouteImport,
});
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: "/admin/analytics",
  path: "/admin/analytics",
  getParentRoute: () => rootRouteImport,
});
const BookingConfirmedBookingIdRoute =
  BookingConfirmedBookingIdRouteImport.update({
    id: "/booking/confirmed/$bookingId",
    path: "/booking/confirmed/$bookingId",
    getParentRoute: () => rootRouteImport,
  });
const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  ForumRoute: ForumRoute,
  LoginRoute: LoginRoute,
  MaterialsRoute: MaterialsRoute,
  NotificationsRoute: NotificationsRoute,
  PeerLearningRoute: PeerLearningRoute,
  PlacementsRoute: PlacementsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RegisteredRoute: RegisteredRoute,
  SettingsRoute: SettingsRoute,
  TeamsRoute: TeamsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminEventsRoute: AdminEventsRoute,
  ClubsClubIdRoute: ClubsClubIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  BookingIndexRoute: BookingIndexRoute,
  ClubsIndexRoute: ClubsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  BookingConfirmedBookingIdRoute: BookingConfirmedBookingIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes();
