/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AssistantRouteImport } from './../routes/assistant'
import { Route as ChatRouteImport } from './../routes/chat'
import { Route as DashboardRouteImport } from './../routes/dashboard'
import { Route as FeedRouteImport } from './../routes/feed'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as MaterialsRouteImport } from './../routes/materials'
import { Route as NotificationsRouteImport } from './../routes/notifications'
import { Route as PeerLearningRouteImport } from './../routes/peer-learning'
import { Route as PlacementsRouteImport } from './../routes/placements'
import { Route as ProfileRouteImport } from './../routes/profile'
import { Route as RegisterRouteImport } from './../routes/register'
import { Route as RegisteredRouteImport } from './../routes/registered'
import { Route as SettingsRouteImport } from './../routes/settings'
import { Route as TeamsRouteImport } from './../routes/teams'
import { Route as AdminIndexRouteImport } from './../routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './../routes/admin.analytics'
import { Route as AdminEventsRouteImport } from './../routes/admin.events'
import { Route as BookingIndexRouteImport } from './../routes/booking.index'
import { Route as ClubsIndexRouteImport } from './../routes/clubs.index'
import { Route as ClubsClubIdRouteImport } from './../routes/clubs.$clubId'
import { Route as EventsIndexRouteImport } from './../routes/events.index'
import { Route as EventsEventIdRouteImport } from './../routes/events.$eventId'
import { Route as BookingConfirmedBookingIdRouteImport } from './../routes/booking.confirmed.$bookingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PeerLearningRoute = PeerLearningRouteImport.update({
  id: '/peer-learning',
  path: '/peer-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementsRoute = PlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisteredRoute = RegisteredRouteImport.update({
  id: '/registered',
  path: '/registered',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIndexRoute = BookingIndexRouteImport.update({
  id: '/booking/',
  path: '/booking/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsClubIdRoute = ClubsClubIdRouteImport.update({
  id: '/clubs/$clubId',
  path: '/clubs/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedBookingIdRoute =
  BookingConfirmedBookingIdRouteImport.update({
    id: '/booking/confirmed/$bookingId',
    path: '/booking/confirmed/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/notifications': typeof NotificationsRoute
  '/peer-learning': typeof PeerLearningRoute
  '/placements': typeof PlacementsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/registered': typeof RegisteredRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/events': typeof AdminEventsRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/booking/': typeof BookingIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/booking/confirmed/$bookingId': typeof BookingConfirmedBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/notifications': typeof NotificationsRoute
  '/peer-learning': typeof PeerLearningRoute
  '/placements': typeof PlacementsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/registered': typeof RegisteredRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/events': typeof AdminEventsRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin': typeof AdminIndexRoute
  '/booking': typeof BookingIndexRoute
  '/clubs': typeof ClubsIndexRoute
  '/events': typeof EventsIndexRoute
  '/booking/confirmed/$bookingId': typeof BookingConfirmedBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/notifications': typeof NotificationsRoute
  '/peer-learning': typeof PeerLearningRoute
  '/placements': typeof PlacementsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/registered': typeof RegisteredRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/events': typeof AdminEventsRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/booking/': typeof BookingIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/booking/confirmed/$bookingId': typeof BookingConfirmedBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/chat'
    | '/dashboard'
    | '/feed'
    | '/login'
    | '/materials'
    | '/notifications'
    | '/peer-learning'
    | '/placements'
    | '/profile'
    | '/register'
    | '/registered'
    | '/settings'
    | '/teams'
    | '/admin/analytics'
    | '/admin/events'
    | '/clubs/$clubId'
    | '/events/$eventId'
    | '/admin/'
    | '/booking/'
    | '/clubs/'
    | '/events/'
    | '/booking/confirmed/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/chat'
    | '/dashboard'
    | '/feed'
    | '/login'
    | '/materials'
    | '/notifications'
    | '/peer-learning'
    | '/placements'
    | '/profile'
    | '/register'
    | '/registered'
    | '/settings'
    | '/teams'
    | '/admin/analytics'
    | '/admin/events'
    | '/clubs/$clubId'
    | '/events/$eventId'
    | '/admin'
    | '/booking'
    | '/clubs'
    | '/events'
    | '/booking/confirmed/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/chat'
    | '/dashboard'
    | '/feed'
    | '/login'
    | '/materials'
    | '/notifications'
    | '/peer-learning'
    | '/placements'
    | '/profile'
    | '/register'
    | '/registered'
    | '/settings'
    | '/teams'
    | '/admin/analytics'
    | '/admin/events'
    | '/clubs/$clubId'
    | '/events/$eventId'
    | '/admin/'
    | '/booking/'
    | '/clubs/'
    | '/events/'
    | '/booking/confirmed/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  MaterialsRoute: typeof MaterialsRoute
  NotificationsRoute: typeof NotificationsRoute
  PeerLearningRoute: typeof PeerLearningRoute
  PlacementsRoute: typeof PlacementsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RegisteredRoute: typeof RegisteredRoute
  SettingsRoute: typeof SettingsRoute
  TeamsRoute: typeof TeamsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  ClubsClubIdRoute: typeof ClubsClubIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BookingIndexRoute: typeof BookingIndexRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  BookingConfirmedBookingIdRoute: typeof BookingConfirmedBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peer-learning': {
      id: '/peer-learning'
      path: '/peer-learning'
      fullPath: '/peer-learning'
      preLoaderRoute: typeof PeerLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placements': {
      id: '/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof PlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registered': {
      id: '/registered'
      path: '/registered'
      fullPath: '/registered'
      preLoaderRoute: typeof RegisteredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/': {
      id: '/booking/'
      path: '/booking'
      fullPath: '/booking/'
      preLoaderRoute: typeof BookingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$clubId': {
      id: '/clubs/$clubId'
      path: '/clubs/$clubId'
      fullPath: '/clubs/$clubId'
      preLoaderRoute: typeof ClubsClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirmed/$bookingId': {
      id: '/booking/confirmed/$bookingId'
      path: '/booking/confirmed/$bookingId'
      fullPath: '/booking/confirmed/$bookingId'
      preLoaderRoute: typeof BookingConfirmedBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  MaterialsRoute: MaterialsRoute,
  NotificationsRoute: NotificationsRoute,
  PeerLearningRoute: PeerLearningRoute,
  PlacementsRoute: PlacementsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RegisteredRoute: RegisteredRoute,
  SettingsRoute: SettingsRoute,
  TeamsRoute: TeamsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminEventsRoute: AdminEventsRoute,
  ClubsClubIdRoute: ClubsClubIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  BookingIndexRoute: BookingIndexRoute,
  ClubsIndexRoute: ClubsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  BookingConfirmedBookingIdRoute: BookingConfirmedBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../router.jsx'
import type { startInstance } from '../start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
