export const currentStudent = {
  id: "u-1",
  name: "Aisha Rahman",
  email: "aisha.rahman@university.edu",
  role: "student",
  major: "Computer Science",
  year: "Third Year",
  bio: "Building things for campus. Robotics club lead dev, hackathon regular, coffee-fuelled.",
  initials: "AR",
  interests: ["Robotics", "Machine Learning", "Debate", "Photography"],
};
export const posts = [
  {
    id: "p-1",
    author: "Office of Student Affairs",
    initials: "SA",
    handle: "@studentaffairs",
    time: "12m",
    body: "Fall registration for elective seminars opens tomorrow at 9:00 AM. Priority windows apply for final-year students.",
    tag: "Announcement",
    likes: 142,
    comments: 23,
  },
  {
    id: "p-2",
    author: "Robotics Society",
    initials: "RS",
    handle: "@robotics",
    time: "1h",
    body: "Our line-follower bot took second place at the inter-university sprint. Build logs and CAD files are now in the shared drive.",
    tag: "Club",
    likes: 318,
    comments: 47,
  },
  {
    id: "p-3",
    author: "Library Services",
    initials: "LS",
    handle: "@library",
    time: "3h",
    body: "Group study rooms on level 4 are now bookable in 90-minute blocks through CampusConnect Resource Booking.",
    tag: "Facilities",
    likes: 96,
    comments: 8,
  },
  {
    id: "p-4",
    author: "Debate Union",
    initials: "DU",
    handle: "@debate",
    time: "6h",
    body: "Motion for Friday's open floor: 'This house would make AI literacy a graduation requirement.' Sign-ups close Thursday noon.",
    tag: "Club",
    likes: 204,
    comments: 61,
  },
  {
    id: "p-5",
    author: "Career Centre",
    initials: "CC",
    handle: "@careers",
    time: "1d",
    body: "Autumn recruitment fair confirmed 48 employers across engineering, finance and health sciences. Book a CV review slot early.",
    tag: "Careers",
    likes: 411,
    comments: 39,
  },
];
export const events = [
  {
    id: "e-1",
    title: "Autumn Hackathon 2026",
    club: "Computing Society",
    date: "Fri, 14 Aug",
    time: "09:00 – 21:00",
    venue: "Innovation Hall, Block C",
    category: "Tech",
    seats: 200,
    taken: 164,
    summary: "Twelve hours, four tracks, one campus-scale problem to solve.",
    details:
      "Teams of up to four build a working prototype against one of four tracks: campus sustainability, accessibility, student wellbeing, or open innovation. Mentors from four partner companies rotate through the hall. Hardware kits, meals and caffeine provided. Judging opens at 19:30 with prizes announced at 20:45.",
  },
  {
    id: "e-2",
    title: "Inter-Faculty Debate Final",
    club: "Debate Union",
    date: "Sat, 15 Aug",
    time: "16:00 – 18:30",
    venue: "Grand Auditorium",
    category: "Culture",
    seats: 400,
    taken: 287,
    summary: "Engineering meets Law in the closing round of the season.",
    details:
      "The final of the inter-faculty season, adjudicated by a panel of three alumni judges. British Parliamentary format, two prepared motions and one impromptu round. Doors open thirty minutes early; late entry is not permitted once the first speech begins.",
  },
  {
    id: "e-3",
    title: "Photography Walk: Old Quarter",
    club: "Lens Club",
    date: "Sun, 16 Aug",
    time: "07:00 – 10:00",
    venue: "Meet at North Gate",
    category: "Arts",
    seats: 40,
    taken: 31,
    summary: "Golden-hour street photography with editing clinic afterwards.",
    details:
      "A guided three-hour walk through the old quarter, focused on natural light and candid composition. Any camera welcome, phones included. The walk finishes with a one-hour editing clinic in the media lab where two club leads review shots live.",
  },
  {
    id: "e-4",
    title: "Founders Night: Campus Startups",
    club: "Entrepreneurship Cell",
    date: "Tue, 18 Aug",
    time: "18:30 – 21:00",
    venue: "Business School Atrium",
    category: "Careers",
    seats: 150,
    taken: 98,
    summary: "Five student founders on what actually worked in year one.",
    details:
      "Short talks from five alumni founders who launched while enrolled, followed by an open networking hour. Each founder hosts a table for direct questions on fundraising, co-founder splits, and balancing a build with coursework.",
  },
  {
    id: "e-5",
    title: "Wellness Week: Yoga at Dawn",
    club: "Student Wellbeing",
    date: "Wed, 19 Aug",
    time: "06:30 – 07:30",
    venue: "Central Lawn",
    category: "Wellbeing",
    seats: 80,
    taken: 44,
    summary: "Slow flow session open to every experience level.",
    details:
      "An hour of gentle vinyasa on the central lawn led by a certified instructor from the campus health service. Mats are provided on a first-come basis; bring water. Session runs rain or shine, moving indoors to Sports Hall B if needed.",
  },
  {
    id: "e-6",
    title: "AI Research Symposium",
    club: "Postgraduate Council",
    date: "Thu, 20 Aug",
    time: "10:00 – 16:00",
    venue: "Science Complex, Room 210",
    category: "Tech",
    seats: 120,
    taken: 112,
    summary: "Nine short papers from across four research groups.",
    details:
      "Nine fifteen-minute presentations spanning representation learning, applied NLP, robotics perception and AI policy. A poster session runs over lunch. Open to undergraduates considering postgraduate study, with an advising desk in the foyer.",
  },
];
export const clubs = [
  {
    id: "c-1",
    name: "Robotics Society",
    category: "Engineering",
    members: 214,
    lead: "Marcus Ortega",
    blurb: "Autonomous systems, combat bots and a very messy workshop.",
    about:
      "The Robotics Society runs three competitive teams and an open workshop every Wednesday evening. Members get access to the fabrication lab, printer queue and a shared component library. No prior experience is required for the beginner build track.",
    emoji: "🤖",
  },
  {
    id: "c-2",
    name: "Debate Union",
    category: "Academic",
    members: 168,
    lead: "Priya Nair",
    blurb:
      "British Parliamentary training, weekly open floors, national circuit.",
    about:
      "One of the oldest societies on campus, the Debate Union trains speakers from complete beginners to national-circuit competitors. Weekly sessions alternate between skills workshops and full practice rounds with adjudicator feedback.",
    emoji: "🎙️",
  },
  {
    id: "c-3",
    name: "Lens Club",
    category: "Arts",
    members: 132,
    lead: "Daniel Okafor",
    blurb: "Photo walks, darkroom access and a termly print exhibition.",
    about:
      "Lens Club welcomes every format from film to phone. The club maintains a working darkroom, lends out four bodies and a small lens pool, and curates an exhibition in the arts foyer at the close of each term.",
    emoji: "📷",
  },
  {
    id: "c-4",
    name: "Entrepreneurship Cell",
    category: "Business",
    members: 189,
    lead: "Sara Lindqvist",
    blurb: "Idea clinics, pitch nights and a small pre-seed grant pool.",
    about:
      "E-Cell connects student founders with alumni mentors, runs a fortnightly idea clinic, and administers a small pre-seed grant awarded twice per year. Past teams have gone on to raise externally in fintech and climate hardware.",
    emoji: "🚀",
  },
  {
    id: "c-5",
    name: "Computing Society",
    category: "Engineering",
    members: 302,
    lead: "Yusuf Karim",
    blurb: "Hackathons, study jams and the campus CTF team.",
    about:
      "The largest technical society on campus. Runs the autumn hackathon, weekly language study jams, and the competitive capture-the-flag squad. Members maintain the open-source tooling behind several student services.",
    emoji: "💻",
  },
  {
    id: "c-6",
    name: "Student Wellbeing",
    category: "Community",
    members: 241,
    lead: "Hannah Boateng",
    blurb: "Peer support, wellness week and quiet-hour study spaces.",
    about:
      "A peer-led network working alongside the campus health service. Trains volunteer listeners each semester, coordinates Wellness Week, and reserves quiet-hour study spaces during examination periods.",
    emoji: "🌿",
  },
];
export const rooms = [
  {
    id: "r-1",
    name: "Study Pod 4B",
    building: "Main Library",
    capacity: 6,
    perks: ["Whiteboard", "Display", "Quiet zone"],
  },
  {
    id: "r-2",
    name: "Seminar Room 210",
    building: "Science Complex",
    capacity: 30,
    perks: ["Projector", "Mic", "Recording"],
  },
  {
    id: "r-3",
    name: "Maker Bay",
    building: "Innovation Hall",
    capacity: 12,
    perks: ["3D printers", "Bench tools", "Storage"],
  },
  {
    id: "r-4",
    name: "Atrium Stage",
    building: "Business School",
    capacity: 120,
    perks: ["PA system", "Lighting", "Livestream"],
  },
  {
    id: "r-5",
    name: "Music Room C",
    building: "Arts Building",
    capacity: 8,
    perks: ["Soundproofed", "Piano", "Interface"],
  },
  {
    id: "r-6",
    name: "Group Room 7",
    building: "Main Library",
    capacity: 4,
    perks: ["Whiteboard", "Power hub"],
  },
];
export const timeSlots = [
  "08:00 – 09:30",
  "09:30 – 11:00",
  "11:00 – 12:30",
  "13:00 – 14:30",
  "14:30 – 16:00",
  "16:00 – 17:30",
  "18:00 – 19:30",
];
export const notices = [
  {
    id: "n-1",
    title: "Autumn Hackathon confirmed",
    body: "Your registration for Autumn Hackathon 2026 is confirmed. QR pass is ready.",
    time: "8m ago",
    kind: "event",
  },
  {
    id: "n-2",
    title: "Marcus mentioned you",
    body: '"@aisha can you take the perception module for the sprint demo?"',
    time: "34m ago",
    kind: "chat",
  },
  {
    id: "n-3",
    title: "Robotics Society posted",
    body: "New build logs and CAD files uploaded to the shared drive.",
    time: "1h ago",
    kind: "club",
  },
  {
    id: "n-4",
    title: "Booking reminder",
    body: "Study Pod 4B is reserved for you tomorrow, 13:00 – 14:30.",
    time: "3h ago",
    kind: "system",
  },
  {
    id: "n-5",
    title: "Debate Union",
    body: "Sign-ups for Friday's open floor close Thursday at noon.",
    time: "5h ago",
    kind: "club",
  },
  {
    id: "n-6",
    title: "Profile strength",
    body: "Add two more interests to reach a complete profile.",
    time: "1d ago",
    kind: "system",
  },
];
export const chatChannels = [
  {
    id: "ch-1",
    name: "Robotics Society",
    emoji: "🤖",
    unread: 3,
    last: "Marcus: sprint demo at 4?",
  },
  {
    id: "ch-2",
    name: "Hackathon Team",
    emoji: "💻",
    unread: 0,
    last: "Yusuf: pushed the auth branch",
  },
  {
    id: "ch-3",
    name: "CS Year 3",
    emoji: "🎓",
    unread: 7,
    last: "Priya: anyone got the lab sheet?",
  },
  {
    id: "ch-4",
    name: "Lens Club",
    emoji: "📷",
    unread: 0,
    last: "Daniel: golden hour is 06:52",
  },
  {
    id: "ch-5",
    name: "Campus General",
    emoji: "🏛️",
    unread: 1,
    last: "Library: level 4 rooms open",
  },
];
export const seedMessages = {
  "ch-1": [
    {
      id: "m1",
      from: "Marcus Ortega",
      initials: "MO",
      body: "Sprint demo is locked for 16:00 in the Maker Bay.",
      time: "14:02",
    },
    {
      id: "m2",
      from: "Aisha Rahman",
      initials: "AR",
      body: "Perception module is passing on the test track, I'll bring the logs.",
      time: "14:05",
      me: true,
    },
    {
      id: "m3",
      from: "Lena Fischer",
      initials: "LF",
      body: "Battery pack B is still drifting under load — swapping to the spare.",
      time: "14:09",
    },
    {
      id: "m4",
      from: "Marcus Ortega",
      initials: "MO",
      body: "Good call. @aisha can you take the perception walkthrough in the demo?",
      time: "14:11",
    },
  ],
  "ch-2": [
    {
      id: "m1",
      from: "Yusuf Karim",
      initials: "YK",
      body: "Pushed the auth branch, review when you get a second.",
      time: "11:20",
    },
    {
      id: "m2",
      from: "Aisha Rahman",
      initials: "AR",
      body: "On it after the lab.",
      time: "11:41",
      me: true,
    },
  ],
  "ch-3": [
    {
      id: "m1",
      from: "Priya Nair",
      initials: "PN",
      body: "Anyone got the distributed systems lab sheet?",
      time: "09:15",
    },
    {
      id: "m2",
      from: "Tom Weaver",
      initials: "TW",
      body: "Uploaded it to the drive, folder Week 6.",
      time: "09:22",
    },
  ],
  "ch-4": [
    {
      id: "m1",
      from: "Daniel Okafor",
      initials: "DO",
      body: "Golden hour is 06:52 on Sunday — meet at North Gate 06:40.",
      time: "20:04",
    },
  ],
  "ch-5": [
    {
      id: "m1",
      from: "Library Services",
      initials: "LS",
      body: "Level 4 group rooms are now bookable in 90-minute blocks.",
      time: "08:00",
    },
  ],
};
export const engagementByMonth = [
  {
    month: "Feb",
    events: 18,
    signups: 412,
    posts: 240,
  },
  {
    month: "Mar",
    events: 24,
    signups: 588,
    posts: 310,
  },
  {
    month: "Apr",
    events: 21,
    signups: 502,
    posts: 288,
  },
  {
    month: "May",
    events: 29,
    signups: 741,
    posts: 366,
  },
  {
    month: "Jun",
    events: 26,
    signups: 690,
    posts: 402,
  },
  {
    month: "Jul",
    events: 34,
    signups: 918,
    posts: 471,
  },
];
export const categorySplit = [
  {
    name: "Tech",
    value: 34,
  },
  {
    name: "Culture",
    value: 22,
  },
  {
    name: "Careers",
    value: 18,
  },
  {
    name: "Arts",
    value: 14,
  },
  {
    name: "Wellbeing",
    value: 12,
  },
];
