export const subjects = [
  "Data Structures",
  "Operating Systems",
  "Machine Learning",
  "DBMS",
  "Computer Networks",
  "Mathematics III",
];
export const notes = [
  {
    id: "nt-1",
    title: "Graph Algorithms — Complete Handwritten Notes",
    subject: "Data Structures",
    type: "Notes",
    author: "Aisha Rahman",
    initials: "AR",
    pages: 42,
    size: "6.4 MB",
    rating: 4.8,
    ratings: 126,
    downloads: 1840,
    uploaded: "2 days ago",
    status: "approved",
    summary:
      "BFS, DFS, Dijkstra, Bellman-Ford, MST with dry runs and 30 solved problems.",
    comments: [
      {
        id: "cm-1",
        author: "Yusuf Karim",
        initials: "YK",
        body: "The Dijkstra dry run finally made it click. Thank you!",
        time: "1d ago",
      },
      {
        id: "cm-2",
        author: "Priya Nair",
        initials: "PN",
        body: "Could you add Floyd-Warshall in the next revision?",
        time: "8h ago",
      },
    ],
  },
  {
    id: "nt-2",
    title: "Operating Systems — Deadlock & Scheduling",
    subject: "Operating Systems",
    type: "Notes",
    author: "Marcus Ortega",
    initials: "MO",
    pages: 28,
    size: "3.1 MB",
    rating: 4.6,
    ratings: 88,
    downloads: 1204,
    uploaded: "5 days ago",
    status: "approved",
    summary:
      "Banker's algorithm, RR/SJF/priority scheduling with Gantt charts.",
    comments: [
      {
        id: "cm-3",
        author: "Lena Fischer",
        initials: "LF",
        body: "Gantt charts are gold before the mid-sem.",
        time: "3d ago",
      },
    ],
  },
  {
    id: "nt-3",
    title: "Machine Learning — Unit 1 to 3 Summary",
    subject: "Machine Learning",
    type: "Notes",
    author: "Priya Nair",
    initials: "PN",
    pages: 36,
    size: "5.2 MB",
    rating: 4.9,
    ratings: 211,
    downloads: 2610,
    uploaded: "1 week ago",
    status: "approved",
    summary:
      "Regression, regularisation, SVM and tree ensembles distilled into exam-ready sheets.",
    comments: [],
  },
  {
    id: "nt-4",
    title: "DBMS Previous Year Questions (2019–2025)",
    subject: "DBMS",
    type: "PYQ",
    author: "Tom Weaver",
    initials: "TW",
    pages: 54,
    size: "8.9 MB",
    rating: 4.7,
    ratings: 143,
    downloads: 3120,
    uploaded: "3 days ago",
    status: "approved",
    summary:
      "Six years of end-sem papers grouped by unit with marking schemes.",
    comments: [
      {
        id: "cm-4",
        author: "Aisha Rahman",
        initials: "AR",
        body: "Unit 4 repeats almost every year — worth prioritising.",
        time: "2d ago",
      },
    ],
  },
  {
    id: "nt-5",
    title: "Computer Networks Assignment 2 — Solutions",
    subject: "Computer Networks",
    type: "Assignment",
    author: "Yusuf Karim",
    initials: "YK",
    pages: 12,
    size: "1.8 MB",
    rating: 4.3,
    ratings: 47,
    downloads: 640,
    uploaded: "Yesterday",
    status: "pending",
    summary:
      "Subnetting, sliding window and TCP congestion control worked solutions.",
    comments: [],
  },
  {
    id: "nt-6",
    title: "Mathematics III — Laplace & Fourier Cheatsheet",
    subject: "Mathematics III",
    type: "Notes",
    author: "Lena Fischer",
    initials: "LF",
    pages: 8,
    size: "0.9 MB",
    rating: 4.5,
    ratings: 72,
    downloads: 980,
    uploaded: "4 days ago",
    status: "pending",
    summary: "Every transform pair and property on two printable pages.",
    comments: [],
  },
];
export const learningRequests = [
  {
    id: "lr-1",
    student: "Yusuf Karim",
    initials: "YK",
    subject: "Data Structures",
    topic: "Segment trees with lazy propagation",
    description:
      "Struggling with range update queries. Looking for someone to walk through two problems with me.",
    preferredTime: "Today, 18:00",
    mode: "Online",
    posted: "12m ago",
    status: "open",
  },
  {
    id: "lr-2",
    student: "Priya Nair",
    initials: "PN",
    subject: "Machine Learning",
    topic: "Backpropagation intuition",
    description:
      "I can do the maths but not explain it. Want a peer session to reason through a tiny network by hand.",
    preferredTime: "Tomorrow, 11:00",
    mode: "Offline",
    posted: "48m ago",
    status: "open",
  },
  {
    id: "lr-3",
    student: "Tom Weaver",
    initials: "TW",
    subject: "Operating Systems",
    topic: "Banker's algorithm practice",
    description:
      "Need a study buddy for 45 minutes of past-paper deadlock questions before Friday.",
    preferredTime: "Thu, 15:30",
    mode: "Online",
    posted: "2h ago",
    status: "open",
  },
  {
    id: "lr-4",
    student: "Lena Fischer",
    initials: "LF",
    subject: "DBMS",
    topic: "Normalisation up to BCNF",
    description:
      "Confused between 3NF and BCNF decomposition. Offline in the library works best for me.",
    preferredTime: "Fri, 14:00",
    mode: "Offline",
    posted: "5h ago",
    status: "open",
  },
  {
    id: "lr-5",
    student: "Marcus Ortega",
    initials: "MO",
    subject: "Computer Networks",
    topic: "TCP congestion control",
    description:
      "Looking to co-teach: I explain routing, you explain congestion windows.",
    preferredTime: "Sat, 10:00",
    mode: "Online",
    posted: "1d ago",
    status: "open",
  },
];
export const forumQuestions = [
  {
    id: "q-1",
    title: "How do I choose between BFS and Dijkstra for weighted graphs?",
    body: "My edges have weights of 0 and 1 only. Is plain BFS enough or do I need a priority queue?",
    subject: "Data Structures",
    author: "Yusuf Karim",
    initials: "YK",
    time: "20m ago",
    votes: 34,
    pinned: true,
    trending: true,
    answers: [
      {
        id: "a-1",
        author: "Aisha Rahman",
        initials: "AR",
        body: "Use 0-1 BFS with a deque — push 0-weight edges to the front. O(V+E) instead of O(E log V).",
        votes: 27,
        time: "12m ago",
      },
      {
        id: "a-2",
        author: "Marcus Ortega",
        initials: "MO",
        body: "Dijkstra still works, it's just heavier than it needs to be here.",
        votes: 9,
        time: "5m ago",
      },
    ],
  },
  {
    id: "q-2",
    title:
      "Is a semaphore always better than a mutex for the reader-writer problem?",
    body: "Our lab solution uses two semaphores but the textbook prefers a monitor. Which is expected in the exam?",
    subject: "Operating Systems",
    author: "Lena Fischer",
    initials: "LF",
    time: "1h ago",
    votes: 21,
    trending: true,
    answers: [
      {
        id: "a-3",
        author: "Tom Weaver",
        initials: "TW",
        body: "Either is accepted if you state the invariant. Monitors are cleaner to defend in a viva.",
        votes: 14,
        time: "40m ago",
      },
    ],
  },
  {
    id: "q-3",
    title: "Why does my validation loss go up while training loss falls?",
    body: "Small dataset, 3-layer MLP, no dropout. Is this always overfitting or could it be the learning rate?",
    subject: "Machine Learning",
    author: "Priya Nair",
    initials: "PN",
    time: "3h ago",
    votes: 48,
    trending: true,
    answers: [
      {
        id: "a-4",
        author: "Aisha Rahman",
        initials: "AR",
        body: "Classic overfitting. Add dropout or weight decay and early-stop on validation loss.",
        votes: 31,
        time: "2h ago",
      },
    ],
  },
  {
    id: "q-4",
    title:
      "BCNF decomposition losing a functional dependency — is that allowed?",
    body: "My decomposition is lossless but not dependency preserving. Do I lose marks for that?",
    subject: "DBMS",
    author: "Tom Weaver",
    initials: "TW",
    time: "Yesterday",
    votes: 12,
    answers: [],
  },
  {
    id: "q-5",
    title: "Best resource for subnetting practice?",
    body: "Looking for a drill set with answers, not theory.",
    subject: "Computer Networks",
    author: "Marcus Ortega",
    initials: "MO",
    time: "2d ago",
    votes: 8,
    answers: [
      {
        id: "a-5",
        author: "Yusuf Karim",
        initials: "YK",
        body: "The PYQ pack in Study Materials has 60 subnetting questions with solutions.",
        votes: 6,
        time: "1d ago",
      },
    ],
  },
];
export const teams = [
  {
    id: "tm-1",
    name: "CampusVision",
    projectType: "Hackathon",
    lead: "Marcus Ortega",
    skills: ["React", "Computer Vision", "Python"],
    members: [
      {
        name: "Marcus Ortega",
        initials: "MO",
      },
      {
        name: "Lena Fischer",
        initials: "LF",
      },
    ],
    slots: 2,
    blurb:
      "Accessibility navigation app for the autumn hackathon. Need a frontend dev and a CV engineer.",
  },
  {
    id: "tm-2",
    name: "Thesis Study Circle",
    projectType: "Research",
    lead: "Priya Nair",
    skills: ["LaTeX", "Statistics", "Academic Writing"],
    members: [
      {
        name: "Priya Nair",
        initials: "PN",
      },
    ],
    slots: 3,
    blurb:
      "Weekly accountability group for final-year thesis writing with peer review rounds.",
  },
  {
    id: "tm-3",
    name: "OS Lab Squad",
    projectType: "Coursework",
    lead: "Tom Weaver",
    skills: ["C", "Linux", "Debugging"],
    members: [
      {
        name: "Tom Weaver",
        initials: "TW",
      },
      {
        name: "Yusuf Karim",
        initials: "YK",
      },
      {
        name: "Aisha Rahman",
        initials: "AR",
      },
    ],
    slots: 1,
    blurb:
      "Four-person group for the kernel scheduling assignment. One seat left.",
  },
  {
    id: "tm-4",
    name: "Placement Prep Pod",
    projectType: "Interview Prep",
    lead: "Yusuf Karim",
    skills: ["DSA", "System Design", "Mock Interviews"],
    members: [
      {
        name: "Yusuf Karim",
        initials: "YK",
      },
      {
        name: "Priya Nair",
        initials: "PN",
      },
    ],
    slots: 4,
    blurb:
      "Daily 45-minute mock interviews rotating between DSA and system design.",
  },
];
export const placements = [
  {
    id: "pl-1",
    role: "Software Engineer Intern",
    company: "Northwind Systems",
    logo: "🌐",
    type: "Internship",
    location: "Remote",
    stipend: "₹60,000 / month",
    eligibility: "CGPA ≥ 7.5 · 3rd year CS/IT",
    deadline: "12 Aug 2026",
    description:
      "Six-month internship on the platform team building internal developer tooling in TypeScript and Go.",
    skills: ["TypeScript", "Go", "REST"],
  },
  {
    id: "pl-2",
    role: "Data Science Intern",
    company: "Helix Analytics",
    logo: "📊",
    type: "Internship",
    location: "Bengaluru",
    stipend: "₹45,000 / month",
    eligibility: "CGPA ≥ 8.0 · Any branch",
    deadline: "18 Aug 2026",
    description:
      "Work with the forecasting team on demand models, feature pipelines and dashboarding.",
    skills: ["Python", "Pandas", "SQL"],
  },
  {
    id: "pl-3",
    role: "Campus Job Drive — Graduate Engineer",
    company: "Vertex Industries",
    logo: "🏭",
    type: "Job Drive",
    location: "On campus · Block C",
    stipend: "₹9.5 LPA",
    eligibility: "Final year · No active backlogs",
    deadline: "22 Aug 2026",
    description:
      "On-campus drive with aptitude round, technical interview and HR round on the same day.",
    skills: ["Aptitude", "OOP", "DBMS"],
  },
  {
    id: "pl-4",
    role: "Frontend Engineer",
    company: "Lumen Labs",
    logo: "✨",
    type: "Full-time",
    location: "Hybrid · Pune",
    stipend: "₹12 LPA",
    eligibility: "Final year · Portfolio required",
    deadline: "29 Aug 2026",
    description:
      "Product-focused frontend role on a design-systems heavy team shipping weekly.",
    skills: ["React", "TypeScript", "CSS"],
  },
  {
    id: "pl-5",
    role: "Product Analyst Intern",
    company: "Orbit Fintech",
    logo: "💳",
    type: "Internship",
    location: "Mumbai",
    stipend: "₹40,000 / month",
    eligibility: "CGPA ≥ 7.0 · 3rd/4th year",
    deadline: "05 Sep 2026",
    description:
      "Own experiment analysis and funnel reporting for the payments product line.",
    skills: ["SQL", "Excel", "Analytics"],
  },
];
export const studySessions = [
  {
    id: "ss-1",
    topic: "Segment trees with Yusuf",
    time: "Today · 18:00",
    mode: "Online",
    initials: "YK",
  },
  {
    id: "ss-2",
    topic: "Backprop walkthrough with Priya",
    time: "Tomorrow · 11:00",
    mode: "Offline",
    initials: "PN",
  },
  {
    id: "ss-3",
    topic: "Deadlock past papers with Tom",
    time: "Thu · 15:30",
    mode: "Online",
    initials: "TW",
  },
];
export const learningProgress = [
  {
    label: "Study minutes",
    value: 78,
    target: "120 min goal",
  },
  {
    label: "Notes reviewed",
    value: 60,
    target: "3 of 5 decks",
  },
  {
    label: "Peer sessions",
    value: 50,
    target: "1 of 2 today",
  },
  {
    label: "Forum activity",
    value: 90,
    target: "9 of 10 points",
  },
];
export const badges = [
  {
    id: "b-1",
    label: "Top Contributor",
    emoji: "🏆",
    note: "Top 5% of note uploaders",
  },
  {
    id: "b-2",
    label: "Peer Mentor",
    emoji: "🤝",
    note: "24 learning requests accepted",
  },
  {
    id: "b-3",
    label: "Quiz Master",
    emoji: "🧠",
    note: "40 AI quizzes completed",
  },
  {
    id: "b-4",
    label: "Streak x30",
    emoji: "🔥",
    note: "30-day learning streak",
  },
];
export const activityTimeline = [
  {
    id: "at-1",
    text: "Accepted a learning request from Yusuf Karim",
    time: "12m ago",
  },
  {
    id: "at-2",
    text: "Uploaded 'Graph Algorithms — Complete Handwritten Notes'",
    time: "2d ago",
  },
  {
    id: "at-3",
    text: "Answered a Data Structures question in the forum",
    time: "3d ago",
  },
  {
    id: "at-4",
    text: "Joined team OS Lab Squad",
    time: "5d ago",
  },
  {
    id: "at-5",
    text: "Applied to Northwind Systems internship",
    time: "1w ago",
  },
];
export const skills = [
  "React",
  "Python",
  "Data Structures",
  "Machine Learning",
  "Public Speaking",
  "LaTeX",
];
export const achievements = [
  {
    id: "ac-1",
    title: "Hackathon Runner-up",
    detail: "Inter-university robotics sprint, 2026",
  },
  {
    id: "ac-2",
    title: "Peer Learning Star",
    detail: "Highest rated mentor in Computer Science",
  },
  {
    id: "ac-3",
    title: "Dean's List",
    detail: "Semester 5, CGPA 9.1",
  },
];
export const aiSuggestions = [
  "Explain time complexity of Dijkstra vs Bellman-Ford",
  "Summarise my Operating Systems notes into 10 bullet points",
  "Generate a 5-question quiz on normalisation",
  "Recommend resources to master backpropagation",
];
export const aiHistory = [
  {
    id: "ah-1",
    title: "Segment tree lazy propagation",
    time: "Today",
  },
  {
    id: "ah-2",
    title: "Summarise ML Unit 2",
    time: "Yesterday",
  },
  {
    id: "ah-3",
    title: "Quiz: TCP congestion control",
    time: "2 days ago",
  },
  {
    id: "ah-4",
    title: "Explain BCNF vs 3NF",
    time: "Last week",
  },
];
export const adminStudents = [
  {
    id: "st-1",
    name: "Aisha Rahman",
    email: "aisha.rahman@university.edu",
    branch: "Computer Science",
    year: "3rd",
    status: "Active",
    notes: 12,
    requests: 24,
  },
  {
    id: "st-2",
    name: "Yusuf Karim",
    email: "yusuf.karim@university.edu",
    branch: "Computer Science",
    year: "3rd",
    status: "Active",
    notes: 8,
    requests: 15,
  },
  {
    id: "st-3",
    name: "Priya Nair",
    email: "priya.nair@university.edu",
    branch: "Information Tech",
    year: "4th",
    status: "Active",
    notes: 19,
    requests: 31,
  },
  {
    id: "st-4",
    name: "Marcus Ortega",
    email: "marcus.ortega@university.edu",
    branch: "Electronics",
    year: "4th",
    status: "Active",
    notes: 6,
    requests: 9,
  },
  {
    id: "st-5",
    name: "Lena Fischer",
    email: "lena.fischer@university.edu",
    branch: "Mechanical",
    year: "2nd",
    status: "Suspended",
    notes: 2,
    requests: 4,
  },
  {
    id: "st-6",
    name: "Tom Weaver",
    email: "tom.weaver@university.edu",
    branch: "Computer Science",
    year: "2nd",
    status: "Active",
    notes: 11,
    requests: 18,
  },
];
export const adminActivity = [
  {
    id: "aa-1",
    text: "Priya Nair uploaded 'ML Unit 4 Summary' — awaiting approval",
    time: "6m ago",
  },
  {
    id: "aa-2",
    text: "18 new learning requests broadcast in the last hour",
    time: "1h ago",
  },
  {
    id: "aa-3",
    text: "Forum post flagged in Operating Systems",
    time: "2h ago",
  },
  {
    id: "aa-4",
    text: "Vertex Industries job drive published",
    time: "4h ago",
  },
  {
    id: "aa-5",
    text: "Robotics Society added 14 new members",
    time: "Yesterday",
  },
];
export const learningByWeek = [
  {
    week: "W1",
    sessions: 42,
    notes: 18,
    questions: 30,
  },
  {
    week: "W2",
    sessions: 58,
    notes: 26,
    questions: 44,
  },
  {
    week: "W3",
    sessions: 51,
    notes: 22,
    questions: 38,
  },
  {
    week: "W4",
    sessions: 74,
    notes: 35,
    questions: 61,
  },
  {
    week: "W5",
    sessions: 69,
    notes: 31,
    questions: 55,
  },
  {
    week: "W6",
    sessions: 88,
    notes: 44,
    questions: 72,
  },
];
export const subjectSplit = [
  {
    name: "Data Structures",
    value: 31,
  },
  {
    name: "Machine Learning",
    value: 24,
  },
  {
    name: "Operating Systems",
    value: 18,
  },
  {
    name: "DBMS",
    value: 15,
  },
  {
    name: "Networks",
    value: 12,
  },
];
export const reports = [
  {
    id: "rp-1",
    title: "Weekly engagement report",
    period: "01 – 07 Aug 2026",
    size: "412 KB",
    type: "Engagement",
  },
  {
    id: "rp-2",
    title: "Study material approvals",
    period: "July 2026",
    size: "268 KB",
    type: "Moderation",
  },
  {
    id: "rp-3",
    title: "Peer learning outcomes",
    period: "Q2 2026",
    size: "1.1 MB",
    type: "Learning",
  },
  {
    id: "rp-4",
    title: "Placement funnel summary",
    period: "July 2026",
    size: "702 KB",
    type: "Placements",
  },
];
export const conversations = [
  {
    id: "cv-1",
    name: "Yusuf Karim",
    emoji: "🧑‍💻",
    online: true,
    unread: 2,
    last: "Sounds good, 18:00 works",
    time: "14:32",
    typing: false,
    kind: "peer",
  },
  {
    id: "cv-2",
    name: "Robotics Society",
    emoji: "🤖",
    online: true,
    unread: 3,
    last: "Marcus: sprint demo at 4?",
    time: "14:02",
    typing: false,
    kind: "group",
  },
  {
    id: "cv-3",
    name: "Priya Nair",
    emoji: "🎓",
    online: false,
    unread: 0,
    last: "Seen · Thanks for the notes!",
    time: "11:47",
    typing: false,
    kind: "peer",
  },
  {
    id: "cv-4",
    name: "OS Lab Squad",
    emoji: "🖥️",
    online: true,
    unread: 0,
    last: "Tom: pushed the scheduler patch",
    time: "10:12",
    typing: false,
    kind: "group",
  },
  {
    id: "cv-5",
    name: "Placement Prep Pod",
    emoji: "💼",
    online: false,
    unread: 1,
    last: "Mock interview at 20:00",
    time: "Yesterday",
    typing: false,
    kind: "group",
  },
];
export const conversationMessages = {
  "cv-1": [
    {
      id: "m1",
      from: "Yusuf Karim",
      initials: "YK",
      body: "Hey! Thanks for accepting my learning request 🙏",
      time: "14:20",
    },
    {
      id: "m2",
      from: "Aisha Rahman",
      initials: "AR",
      body: "Of course. Segment trees, right? Let's do two problems.",
      time: "14:22",
      me: true,
      seen: true,
    },
    {
      id: "m3",
      from: "Yusuf Karim",
      initials: "YK",
      body: "Here's the question set I'm stuck on.",
      time: "14:25",
      attachment: {
        kind: "pdf",
        name: "segment-trees-practice.pdf",
        meta: "PDF · 1.2 MB",
      },
    },
    {
      id: "m4",
      from: "Aisha Rahman",
      initials: "AR",
      body: "Got it. I'll share my whiteboard from last term too.",
      time: "14:28",
      me: true,
      seen: true,
      attachment: {
        kind: "image",
        name: "lazy-propagation-board.png",
        meta: "Image · 840 KB",
      },
    },
    {
      id: "m5",
      from: "Yusuf Karim",
      initials: "YK",
      body: "Sounds good, 18:00 works",
      time: "14:32",
    },
  ],
  "cv-2": [
    {
      id: "m1",
      from: "Marcus Ortega",
      initials: "MO",
      body: "Sprint demo is locked for 16:00 in the Maker Bay.",
      time: "14:02",
    },
    {
      id: "m2",
      from: "Aisha Rahman",
      initials: "AR",
      body: "Perception module passes on the test track — bringing logs.",
      time: "14:05",
      me: true,
      seen: true,
    },
  ],
  "cv-3": [
    {
      id: "m1",
      from: "Priya Nair",
      initials: "PN",
      body: "Thanks for the notes! The ML summary saved my week.",
      time: "11:47",
    },
  ],
  "cv-4": [
    {
      id: "m1",
      from: "Tom Weaver",
      initials: "TW",
      body: "Pushed the scheduler patch, round-robin quantum is configurable now.",
      time: "10:12",
    },
  ],
  "cv-5": [
    {
      id: "m1",
      from: "Yusuf Karim",
      initials: "YK",
      body: "Mock interview at 20:00 — system design round.",
      time: "Yesterday",
    },
  ],
};
